djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('framac/', include('framac.urls'))
]

framac/urls.py
from django.urls import path, include

from . import views

app_name = "framac"

urlpatterns = [
    path('', views.index, name='index'),
    path('add-file/', views.get_file, name='add-file'),
    path('add-directory/', views.get_directory, name='add-directory'),
    path('files/<int:file_id>', views.file_index, name='file'),
    path('files/delete/<int:file_id>', views.delete_file, name='file_delete'),
    path('files/reprove/<int:file_id>', views.reprove, name='reprove'),
    path('directories/<int:directory_id>', views.directory_index, name='directory'),
    path('directories/delete/<int:directory_id>', views.delete_directory, name='directory_delete'),
    path('tabs/prover', views.prover_tab, name='prover'),
    path('tabs/vc', views.vc_tab, name='vc'),
    path('tabs/result/<int:file_id>', views.result, name='result'),
    path('users/', include('django.contrib.auth.urls'))
]

framac/models.py
from django.db import models


class Directory(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=400, blank=True)
    creation_date = models.DateTimeField('creation date')
    owner = models.CharField(max_length=200)
    is_available = models.BooleanField(default=True)
    parent_directory = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

    def list_content(self):
        directory_items = ["directory:begin", self]
        for directory in self.directory_set.all():
            directory_items += directory.list_content()
        for file in self.file_set.all():
            directory_items.append(file)
        directory_items.append("directory:end")
        return directory_items

    def delete_directory(self):
        for directory in self.directory_set.all():
            directory.delete_directory()
        for file in self.file_set.all():
            file.delete_file()
        self.is_available = False
        self.save()


class SectionCategory(models.Model):
    name = models.CharField(max_length=200)


class SectionStatus(models.Model):
    name = models.CharField(max_length=200)


class User(models.Model):
    name = models.CharField(max_length=50)
    login = models.CharField(max_length=40)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.login


class StatusData(models.Model):
    data = models.TextField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)


class FileSection(models.Model):
    name = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=400, blank=True)
    creation_date = models.DateTimeField()
    section_category = models.ForeignKey(SectionCategory, on_delete=models.CASCADE)
    status = models.ForeignKey(SectionStatus, on_delete=models.CASCADE)
    status_data = models.ForeignKey(StatusData, on_delete=models.CASCADE)


class File(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=400, blank=True)
    creation_date = models.DateTimeField()
    owner = models.CharField(max_length=200)
    is_available = models.BooleanField(default=True)
    parent_directory = models.ForeignKey(Directory, on_delete=models.CASCADE)
    file = models.FileField(upload_to='framac/files')
    file_sections = models.ManyToManyField(FileSection)  # change
    result = models.TextField()

    def __str__(self):
        return self.name

    def delete_file(self):
        self.is_available = False
        self.save()


class Prover(models.Model):
    name = models.CharField(max_length=200)
    is_default = models.BooleanField(default=False)


class VC(models.Model):
    name = models.CharField(max_length=200)
    is_default = models.BooleanField(default=False)

framac/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()
    #owner = forms.CharField(max_length=200)
    description = forms.CharField(max_length=400, required=False)
    directory = forms.CharField(max_length=200)


class NewDirectoryForm(forms.Form):
    name = forms.CharField(max_length=50)
    description = forms.CharField(max_length=400, required=False)
    #owner = forms.CharField(max_length=60)
    parent_directory = forms.CharField(max_length=200)


class ProversChooseForm(forms.Form):
    prover_choices = [('alt-ergo', 'Alt-Ergo'), ('z3', 'Z3'), ('cvc4', 'CVC4')]
    prover = forms.ChoiceField(choices=prover_choices)


class VcChooseForm(forms.Form):
    vc_choices = [('-@invariant', 'Invariant')]
    vc = forms.ChoiceField(choices=vc_choices)

framac/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect

from django.http import HttpResponseRedirect
from django.utils import timezone

from .forms import UploadFileForm
from .forms import NewDirectoryForm
from .forms import ProversChooseForm
from .forms import VcChooseForm

from .models import Directory
from .models import StatusData
from .models import FileSection
from .models import SectionCategory
from .models import SectionStatus
from .models import File
from .models import Prover
from .models import VC

import os
import subprocess
import re


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/framac/users/login')
    if not Directory.objects.filter(name='root', owner=request.user.username).exists():
        root = Directory(name='root',
                         owner=request.user.username,
                         description="root directory of the user",
                         creation_date=timezone.now(),
                         is_available=True)
        root.save()
    root_directory = Directory.objects.get(name='root', owner=request.user.username).list_content()
    context = {'root_directory': root_directory,
               'range': range(root_directory.__len__())}
    return render(request, 'framac/index.html', context)


def file_index(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    root_directory = Directory.objects.get(name='root', owner=request.user.username).list_content()
    file_content = get_file_content(file.file)
    file_sections = file.file_sections
    context = {'root_directory': root_directory,
               'range': range(root_directory.__len__()),
               'file_content': file_content,
               'file_sections': file_sections,
               'file_id': file_id}
    return render(request, 'framac/index.html', context)


def directory_index(request, directory_id):
    root_directory = Directory.objects.get(name='root', owner=request.user.username).list_content()
    context = {'root_directory': root_directory,
               'range': range(root_directory.__len__()),
               'directory_id': directory_id}
    return render(request, 'framac/index.html', context)


def delete_file(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    file.delete_file()
    return redirect('framac:index')


def delete_directory(request, directory_id):
    directory = get_object_or_404(Directory, pk=directory_id)
    directory.delete_directory()
    return redirect('framac:index')


def prover_tab(request):
    if request.method == 'POST':
        form = ProversChooseForm(request.POST)
        if form.is_valid():
            change_prover(form.cleaned_data['prover'])
            return HttpResponseRedirect('/framac')
    else:
        form = ProversChooseForm()
    root_directory = Directory.objects.get(name='root', owner=request.user.username).list_content()
    current_prover = Prover.objects.get(is_default=True)
    return render(request, 'framac/index.html', {'form': form,
                                                 'root_directory': root_directory,
                                                 'range': range(root_directory.__len__()),
                                                 'url': "framac:prover",
                                                 'data': "current prover: " + current_prover.name})


def change_prover(prover):
    current = Prover.objects.get(is_default=True)
    current.is_default = False
    current.save()
    new_prover = Prover.objects.get(name=prover)
    new_prover.is_default = True
    new_prover.save()


def vc_tab(request):
    if request.method == 'POST':
        form = VcChooseForm(request.POST)
        if form.is_valid():
            change_vc(form.cleaned_data['vc'])
            return HttpResponseRedirect('/framac')
    else:
        form = VcChooseForm()
    root_directory = Directory.objects.get(name='root', owner=request.user.username).list_content()
    current_vc = VC.objects.get(is_default=True)
    return render(request, 'framac/index.html', {'form': form,
                                                 'root_directory': root_directory,
                                                 'range': range(root_directory.__len__()),
                                                 'url': "framac:vc",
                                                 'data': "current vc: " + current_vc.name})


def change_vc(vc):
    current = VC.objects.get(is_default=True)
    current.is_default = False
    current.save()
    new_vc = VC.objects.get(name=vc)
    new_vc.is_default = True
    new_vc.save()


def result(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    root_directory = Directory.objects.get(name='root', owner=request.user.username).list_content()
    file_content = get_file_content(file.file)
    file_sections = file.file_sections
    context = {'root_directory': root_directory,
               'range': range(root_directory.__len__()),
               'file_content': file_content,
               'file_sections': file_sections,
               'file_id': file_id,
               'data': file.result}
    return render(request, 'framac/index.html', context)


def get_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            new_file(request.user.username, form, request.FILES['file'])
            return HttpResponseRedirect('/framac')
    else:
        form = UploadFileForm()
    return render(request, 'framac/add-file.html', {'form': form})


def get_directory(request):
    if request.method == 'POST':
        form = NewDirectoryForm(request.POST)
        if form.is_valid():
            new_directory(request.user.username, form)
            return HttpResponseRedirect('/framac')
    else:
        form = NewDirectoryForm()
    return render(request, 'framac/add-directory.html', {'form': form})


def new_file(user, form_, file_):
    name = os.path.basename(file_.name)
    owner = user
    description = form_.cleaned_data['description']
    directory = form_.cleaned_data['directory']
    parent_directory = Directory.objects.get(name=directory, owner=user)
    # should exist
    nfile = parent_directory.file_set.create(name=name,
                                             description=description,
                                             owner=owner,
                                             is_available=True,
                                             creation_date=timezone.now(),
                                             file=file_)
    cmd = "frama-c -wp -wp-log=\"r:result.txt\"  " + "framac/files/" + name
    os.system(cmd)
    cmd = "cat result.txt"
    result_file = subprocess.getoutput(cmd)
    nfile.result = result_file
    nfile.save()
    cmd = "frama-c -wp -wp-print " + "framac/files/" + name
    result_file = subprocess.getoutput(cmd)
    parse_file(nfile, result_file)


def reprove(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    name = os.path.basename(file.name)
    cmd = "frama-c -wp -wp-log=\"r:result.txt\"  " + "framac/files/" + name
    os.system(cmd)
    cmd = "cat result.txt"
    new_result = subprocess.getoutput(cmd)
    file.result = new_result
    prover = get_object_or_404(Prover, is_default=True).name
    vc = get_object_or_404(VC, is_default=True).name
    cmd = "frama-c -wp -wp-prover " + prover + " -wp-prop=\" " + vc + "\" -wp-rte -wp-print " + "framac/files/" + name
    new_result = subprocess.getoutput(cmd)
    for section in file.file_sections.all():
        section.delete()
    file.file_sections.clear()
    parse_file(file, new_result)
    return file_index(request, file_id)


def new_directory(user, form_):
    name = form_.cleaned_data['name']
    owner = user
    description = form_.cleaned_data['description']
    directory = form_.cleaned_data['parent_directory']
    parent_directory = Directory.objects.get(name=directory, owner=user)
    parent_directory.directory_set.create(name=name,
                                          owner=owner,
                                          description=description,
                                          creation_date=timezone.now(),
                                          is_available=True)


def parse_file(file, wp_result):
    i = 0
    while i < len(wp_result) and wp_result[i: i + len("----------")] != "----------":
        i += 1
    while i < len(wp_result):
        if is_beginning(wp_result, i):
            section = ""
            while i < len(wp_result) and wp_result[i: i + len("----------")] != "----------":
                section += wp_result[i]
                i += 1
            parse_section_and_add(file, section)
        else:
            i += 1


def parse_section_and_add(file, section):
    category_name = section[len("Goal "):].split("(")[0]
    if SectionCategory.objects.filter(name=category_name).exists():
        section_category = SectionCategory.objects.get(name=category_name)
    else:
        section_category = SectionCategory(name=category_name)
        section_category.save()
    prover_line = re.findall("Prover.*returns.*", section)[0]
    section_status = prover_line.split("returns")[1]
    if SectionStatus.objects.filter(name=section_status).exists():
        section_status_obj = SectionStatus.objects.get(name=section_status)
    else:
        section_status_obj = SectionStatus(name=section_status)
        section_status_obj.save()
    status_data = StatusData(data=section)
    status_data.save()
    file_section = FileSection(creation_date=timezone.now(),
                               section_category=section_category,
                               status=section_status_obj,
                               status_data=status_data)
    file_section.save()
    file.file_sections.add(file_section)


def is_beginning(wp_result, pos):

framac/templates/framac/add-directory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New directory</title>
</head>
<body>
    <form action="{% url 'framac:add-directory' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

framac/templates/framac/add-file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New file</title>
</head>
<body>
    <form action="{% url 'framac:add-file' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

framac/templates/framac/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Frama-C</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'framac/main.css' %}" />
    <link rel="stylesheet" href="{% static "codemirror/lib/codemirror.css"%}">
    <link rel="stylesheet" href="{% static "codemirror/theme/dracula.css"%}">
    <script type="text/javascript" src="{% static "codemirror/lib/codemirror.js"%}"></script>
    <script type="text/javascript" src="{% static "codemirror/mode/clike/clike.js"%}"></script>
</head>
<body>
    <div class="main">
        <div class="menu">
            <ul class="navi">
                <li><a href="/framac/">Frama-c</a></li>
                {% if user.is_authenticated %}
                    <li><a href="/framac/add-file">New file</a></li>
                    <li><a href="/framac/add-directory">New directory</a></li>
                {% endif %}
                {% if file_id %}
                    <li><a href="{% url 'framac:file_delete' file_id %}" class="dynamic">Delete file</a></li>
                    <li><a href="{% url 'framac:reprove' file_id %}" class="dynamic">Rerun verification</a> </li>
                {% endif %}
                {% if directory_id %}
                    <li><a href="{% url 'framac:directory_delete' directory_id %}" class="dynamic">Delete directory</a> </li>
                {% endif %}
            </ul>
        </div>
        <div class="user-space">
            {% if user.is_authenticated %}
                Hi {{ user.username }}!
                <a href="{% url 'framac:logout' %}">Log Out</a>
            {% else %}
                  <a href="{% url 'framac:login' %}">Log In</a>
            {% endif %}
        </div>
        <div class="file-selection">
            <p>Source file</p>
            {% load tags %}
            <ul>
            {% for file in root_directory %}
                {% with next_e=root_directory|next_element:forloop.counter0 %}
                {% with previous_e=root_directory|previous_element:forloop.counter0 %}
                {% if file == "directory:begin" %}
                    {% if next_e.is_available %}
                        <li><a href="{% url 'framac:directory' next_e.id %}" class="dynamic">{{ next_e.name }}</a></li>
                    {% endif %}
                    <ul>
                {% elif file == "directory:end" %}
                    </ul>
                {% elif previous_e != "directory:begin" and file.is_available%}
                    <li><a href="{% url 'framac:file' file.id %}" class="dynamic">{{ file.name }}</a></li>
                {% endif %}
                {% endwith %}
                {% endwith %}
            {% endfor %}
            </ul>
        </div>
        <div class="source-code">
            <textarea id="code-area-main">{{ file_content }}</textarea>
        </div>
        <div class="elements">
            <p>Elements</p>
            <div id="code-area-secondary">
                {% for section in file_sections.all %}
                    <button class="hide-button">Hide</button>
                    <button class="show-button">Show</button>
                    <p>{{ section.status_data.data }}</p>
                    <p class="hidden-status-name">{{ section.status.name }}</p>
                {% endfor %}
            </div>
        </div>
        <div class="tab">
            <ul class="navi">
                <li><a href="{% url 'framac:prover' %}" class="dynamic">Provers</a></li>
                <li><a href="{% url 'framac:vc' %}" class="dynamic">VCs</a></li>
                {% if file_id %}
                    <li><a href="{% url 'framac:result' file_id %}" class="dynamic">Result</a> </li>
                {% endif %}
            </ul>
        </div>
        <div class="tab-data">
            {% csrf_token %}
            {% if form %}
                <form action="{% url url %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Submit">
                </form>
            {% endif %}
            {% if data %}
                {{ data }}
            {% endif %}
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $(".dynamic").click(
                function (e) {
                    e.preventDefault();
                    var resource = $(this).attr('href');
                    //alert(resource)
                    $.ajax({
                            url: resource,
                            success: function (data) {
                                //$("#code-area-secondary").text(data.file_sections)
                                $("body").html(data);
                                $(".hidden-status-name").hide();
                                //$("#code-area-main").text(data)
                                //alert(data);
                            }
                        }
                    );
                }
            );
            $(".hide-button").click(
                function () {
                    var sctn=$(this).next().next().next().text();
                    $(this).next().next().hide();
                    $(this).next().after("<p></p>");
                    $(this).next().next().text(sctn);
                }
            );
            $(".show-button").click(
                function () {
                    $(this).next().remove();
                    $(this).next().show();
                }
            );
            }
        );
    </script>

    <!-- Create a simple CodeMirror instance -->

    <script type="text/javascript">
        var editor = CodeMirror.fromTextArea(document.getElementById("code-area-main"), {
            lineNumbers: true,
            mode: "text/x-csrc",
            theme: "dracula",
            readOnly: true
      });
    </script>

    <script type="text/javascript">


        const comments = document.getElementsByClassName("cm-comment");
          for (var i = 0; i < comments.length; i++) {
            if (comments[i].innerHTML[0] === "@" ||
                (comments[i].innerHTML[0] === "/"
                    && comments[i].innerHTML[1] === "*"
                    && comments[i].innerHTML[2] === "@") ||
                (comments[i].innerHTML[0] === "/"
                    && comments[i].innerHTML[1] === "/"
                    && comments[i].innerHTML[2] === "@")) {
                comments[i].style.color = "yellow";
            }
          }

        const textArea = document.getElementById('code-area-main');

          function change_color() {
              const comments = document.getElementsByClassName("cm-comment");
              for (var i = 0; i < comments.length; i++) {
                if (comments[i].innerHTML[0] === "@" ||
                    (comments[i].innerHTML[0] === "/"
                        && comments[i].innerHTML[1] === "*"
                        && comments[i].innerHTML[2] === "@") ||
                    (comments[i].innerHTML[0] === "/"
                        && comments[i].innerHTML[1] === "/"
                        && comments[i].innerHTML[2] === "@")) {
                    comments[i].style.color = "yellow";
                }
              }
          }

        change_color();

          textArea.onchange(change_color());

    </script>

</body>
</html>